# Updated constants generated by tuner.py
# Apply into chess_engine/classical/constants.py after review.
import numpy as np

MG_MATERIAL_VALUES = np.array([100, 345, 364, 573, 1170, 0], dtype=np.int32)

EG_MATERIAL_VALUES = np.array([120, 422, 436, 690, 1282, 0], dtype=np.int32)

PST_MG = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, -9, -8, -5, -6, -10, -7, 10, 5, -13, -20, -17, -9, -11, -3, -10, -5, -8, -14, -6, 7, 9, -2, 9, -11, 5, -2, -10, 16, 21, 10, -1, 9, 9, 11, 17, 27, 30, 16, 9, 16, 51, 49, 52, 49, 51, 44, 50, 47, 0, 0, 0, 0, 0, 0, 0, 0],
    [-45, -31, -33, -31, -26, -33, -41, -47, -41, -22, -7, -10, -7, 2, -19, -36, -29, -2, -2, 8, 13, 9, 8, -26, -11, 5, 13, 13, 14, 18, -4, -27, -28, 5, 12, 21, 11, 18, 8, -27, -26, 2, 11, 18, 13, 4, 0, -18, -48, -25, -3, 2, 0, -5, -22, -44, -40, -42, -38, -24, -32, -29, -44, -48],
    [-13, -2, -13, -10, -6, -14, -7, -21, -5, -11, 8, -13, 4, 3, 4, -13, -1, 16, -3, 10, 5, 1, 11, -3, -8, 2, 5, 9, 11, 7, -3, -5, -11, 4, 2, 8, 9, 9, -2, -8, -4, 6, 6, 11, 10, 1, 0, -10, -3, 1, 1, -5, 0, -1, -3, -7, -24, -9, -6, -8, -14, -4, -8, -19],
    [-10, 2, 0, 8, 4, -10, -4, 9, -4, 1, -4, 1, 1, 0, -1, -7, -5, -2, 0, -2, 4, -2, 1, -9, -6, 2, 5, 0, -1, 5, -2, -13, -8, 7, 1, 2, -1, 2, 2, -12, -3, 5, -1, -4, 3, -4, 2, -3, 7, 13, 8, 12, 15, 9, 12, 10, 7, -2, 1, 1, -4, -4, 3, -3],
    [-13, -8, -6, -9, -7, -13, -8, -21, -9, 2, 2, 1, -3, 6, 2, -8, -10, 6, 0, -5, 2, 12, 10, -3, 7, 0, 7, -3, 1, 6, 11, -2, -4, 2, 9, -3, 4, 2, 2, 0, -9, 0, 7, 5, 5, 5, -4, -6, -8, -2, 6, 2, -5, 3, 2, -7, -19, -10, -6, -7, -6, -14, -11, -18],
    [17, 33, 15, 2, 17, 11, 26, 20, 20, 22, -2, 0, -12, -6, 22, 20, -5, -17, -21, -20, -16, -23, -21, -10, -16, -30, -27, -42, -42, -35, -23, -18, -26, -41, -42, -50, -51, -38, -36, -32, -26, -35, -41, -54, -46, -38, -41, -27, -33, -37, -40, -50, -51, -40, -41, -26, -27, -45, -40, -52, -50, -37, -36, -30],
], dtype=np.int32)

PST_EG = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 11, 12, 16, 14, 23, 19, 10, 1, 11, 7, 11, 13, 11, 12, 6, 1, 10, 9, 5, 3, 3, 3, 6, 7, 28, 16, 13, 19, 10, 12, 17, 13, 46, 42, 43, 52, 51, 41, 43, 46, 75, 72, 83, 74, 80, 85, 74, 73, 0, 0, 0, 0, 0, 0, 0, 0],
    [-50, -38, -35, -28, -26, -34, -37, -49, -38, -20, -9, -5, -2, 2, -22, -37, -30, -4, 2, 11, 14, -7, -3, -28, -18, -2, 18, 17, 17, 16, 7, -24, -28, -2, 16, 22, 24, 16, 4, -21, -30, 3, 9, 14, 13, 8, 5, -37, -37, -16, -7, 14, 6, -8, -23, -40, -49, -43, -33, -31, -26, -27, -35, -56],
    [-37, -32, -25, -15, -16, -20, -35, -35, -20, -22, -9, -10, -2, -2, -18, -21, -21, 6, 2, 4, 3, -1, 0, -22, -15, 0, 6, 6, 14, 4, 1, -17, -16, 4, 11, 15, 6, 17, -3, -7, -18, 0, 5, 3, 4, 1, -6, -6, -29, -9, -18, 5, 5, -8, -17, -29, -44, -19, -31, -11, -9, -33, -24, -43],
    [-10, -17, -9, -13, -14, -8, -17, -17, -15, -10, -6, -4, -2, -3, -9, -13, 2, 1, -3, 2, -1, -6, 3, 5, -4, 4, 12, 0, -3, 8, 1, -5, -1, 8, 2, 10, 8, -3, -3, -4, 12, -2, 6, 11, 11, 0, -9, 9, 2, 4, 20, 1, 0, 20, 6, 7, 12, 5, 17, 17, 10, 19, 5, 18],
    [-65, -53, -47, -31, -35, -45, -56, -70, -57, -34, -22, -11, -11, -26, -30, -61, -42, -17, -12, -8, -4, -11, -20, -41, -34, -5, 0, 12, 17, 4, -6, -26, -29, 2, 13, 24, 24, 12, -2, -20, -46, -15, -8, 1, 6, -8, -21, -38, -50, -31, -18, -7, 0, -19, -28, -53, -75, -52, -43, -35, -39, -42, -44, -77],
    [-50, -26, -23, -28, -30, -31, -28, -52, -30, -25, -9, -7, -13, -12, -17, -30, -33, -12, 15, 11, 9, 2, -4, -30, -27, -7, 25, 32, 24, 19, -3, -26, -27, -9, 34, 36, 42, 35, -4, -24, -24, -9, 20, 31, 28, 20, -8, -25, -26, -11, -5, -2, -2, -7, -16, -30, -53, -38, -30, -23, -16, -27, -35, -48],
], dtype=np.int32)

KNIGHT_MOBILITY_BONUS = np.array([
    [-17, -26],
    [-16, -20],
    [1, -6],
    [2, 12],
    [2, 12],
    [6, 12],
    [10, 12],
    [11, 13],
    [13, 13],
], dtype=np.int32)

BISHOP_MOBILITY_BONUS = np.array([
    [-10, -18],
    [-1, -11],
    [17, 3],
    [22, 9],
    [26, 19],
    [29, 25],
    [30, 30],
    [32, 33],
    [32, 33],
    [34, 35],
    [44, 35],
    [49, 36],
    [52, 39],
    [61, 41],
], dtype=np.int32)

ROOK_MOBILITY_BONUS = np.array([
    [-27, -32],
    [-4, -1],
    [10, 22],
    [13, 32],
    [13, 38],
    [15, 45],
    [16, 53],
    [18, 55],
    [24, 58],
    [25, 62],
    [26, 66],
    [27, 68],
    [28, 70],
    [28, 71],
    [33, 72],
], dtype=np.int32)

QUEEN_MOBILITY_BONUS = np.array([
    [-26, -10],
    [-14, -3],
    [4, 6],
    [12, 7],
    [20, 17],
    [23, 23],
    [23, 33],
    [28, 33],
    [31, 37],
    [34, 42],
    [36, 42],
    [38, 45],
    [41, 51],
    [41, 51],
    [41, 54],
    [41, 58],
    [43, 62],
    [44, 66],
    [45, 68],
    [53, 69],
    [57, 69],
    [58, 70],
    [60, 73],
    [63, 74],
    [65, 75],
    [66, 87],
    [74, 89],
    [74, 95],
], dtype=np.int32)

BISHOP_PAIR_BONUS = np.array([8, 15], dtype=np.int32)

BISHOP_PAIR_PAWN_SCALE = np.array([19, 32], dtype=np.int32)

ROOK_ON_SEMI_OPEN_FILE_BONUS = np.array([21, 5], dtype=np.int32)

ROOK_ON_OPEN_FILE_BONUS = np.array([24, 15], dtype=np.int32)

PASSED_PAWN_BONUS = np.array([
    [0, 0],
    [3, 4],
    [0, 0],
    [6, 22],
    [27, 40],
    [75, 74],
    [133, 110],
    [0, 0],
], dtype=np.int32)

PASSED_FILE_BONUS = np.array([18, 4], dtype=np.int32)

PASSED_CONNECTED_BONUS = np.array([0, 2, 3, 7, 17, 24, 59, 0], dtype=np.int32)

PASSED_PHALANX_BONUS = np.array([0, 2, 4, 12, 25, 42, 75, 0], dtype=np.int32)

CANDIDATE_PASSER_DIVISOR = 2

PASSED_PATH_SAFE_NONE_ATTACK = 11

PASSED_PATH_SAFE_EDGE_ATTACK = 7

PASSED_PATH_SAFE_BLOCK_ONLY = 3

PASSED_PATH_SUPPORT_BONUS = 4

PASSED_DYNAMICS_MULT = 4

PASSED_DYNAMICS_OFFSET = -11

ISOLATED_PAWN_PENALTY = np.array([-1, -6], dtype=np.int32)

DOUBLED_PAWN_PENALTY = np.array([-20, -37], dtype=np.int32)

BACKWARD_PAWN_PENALTY = np.array([0, -6], dtype=np.int32)

WEAK_LEVER_PENALTY = np.array([-4, -27], dtype=np.int32)

WEAK_UNOPPOSED_PENALTY = np.array([-15, -10], dtype=np.int32)

CONNECTED_BONUS = np.array([0, 1, 4, 4, 7, 38, 69, 0], dtype=np.int32)

CONNECTED_BONUS_EG = np.array([0, 2, 2, 11, 14, 25, 37, 0], dtype=np.int32)

CONNECTED_SUPPORT_WEIGHT = 11

CONNECTED_SUPPORT_WEIGHT_EG = 8

OUTPOST_BONUS_KNIGHT = np.array([
    [0, 0],
    [0, 0],
    [16, 5],
    [28, 17],
    [41, 25],
    [35, 26],
    [24, 5],
    [0, 0],
], dtype=np.int32)

OUTPOST_BONUS_BISHOP = np.array([
    [0, 0],
    [0, 0],
    [2, 2],
    [17, 14],
    [26, 18],
    [26, 17],
    [11, 5],
    [0, 0],
], dtype=np.int32)

REACHABLE_OUTPOST_BONUS = np.array([17, 13], dtype=np.int32)

MINOR_BEHIND_PAWN = np.array([13, 3], dtype=np.int32)

BISHOP_PAWNS_PENALTY = np.array([1, 2], dtype=np.int32)

BISHOP_PAWNS_CENTER_BLOCKED_FACTOR = 1

LONG_DIAGONAL_BISHOP = np.array([22, 4], dtype=np.int32)

TRAPPED_ROOK = np.array([14, 2], dtype=np.int32)

ROOK_ON_QUEEN_FILE = np.array([0, 3], dtype=np.int32)

WEAK_QUEEN = np.array([29, 3], dtype=np.int32)

KING_PROTECTOR = np.array([0, 0], dtype=np.int32)

KING_ATTACK_WEIGHTS = np.array([0, 0, 46, 14, 15, 1], dtype=np.int32)

SAFE_CHECK_QUEEN = 569

SAFE_CHECK_ROOK = 825

SAFE_CHECK_BISHOP = 480

SAFE_CHECK_KNIGHT = 609

KING_DANGER_WEAK_SQ = 114

KING_DANGER_UNSAFE_CHECK = 100

KING_DANGER_BLOCKERS = 71

KING_DANGER_ATTACK_ON_KING_SQ = 19

KING_DANGER_NO_QUEEN = 560

KING_DANGER_NO_QUEEN_ROOKLESS = 810

KING_DANGER_KNIGHT_DEF = 96

KING_DANGER_OFFSET = 0

KING_DANGER_THRESHOLD = 69

SHELTER_STRENGTH = np.array([
    [10, 49, 55, 51, 32, 19, 24, 0],
    [-36, 23, 21, -31, -26, -4, -48, 0],
    [1, 62, 24, 7, 24, -5, -39, 0],
    [-19, -4, -8, -16, -31, -52, -130, 0],
], dtype=np.int32)

UNBLOCKED_STORM = np.array([
    [-68, 219, 130, -71, -40, -36, -39, 0],
    [-30, 15, -92, -34, -29, -9, -19, 0],
    [12, -35, -129, -21, 0, 15, 27, 0],
    [8, 7, -79, -2, 3, 23, 16, 0],
], dtype=np.int32)

BLOCKED_STORM = -61

BLOCKED_STORM_EG = -41

SHELTER_BASE_MG = 19

SHELTER_BASE_EG = 5

KING_PAWN_DIST_PENALTY_EG = -6

PAWNLESS_FLANK = np.array([-13, -55], dtype=np.int32)

FLANK_ATTACKS = np.array([-1, 0], dtype=np.int32)

THREAT_SAFE_PAWN = np.array([70, 41], dtype=np.int32)

THREAT_KNIGHT_ON_QUEEN = np.array([9, 0], dtype=np.int32)

THREAT_SLIDER_ON_QUEEN = np.array([21, 1], dtype=np.int32)

THREAT_BY_MINOR = np.array([
    [4, 17],
    [24, 23],
    [54, 29],
    [74, 58],
    [52, 82],
    [0, 0],
], dtype=np.int32)

THREAT_BY_ROOK = np.array([
    [3, 22],
    [20, 30],
    [27, 26],
    [0, 21],
    [41, 22],
    [0, 0],
], dtype=np.int32)

THREAT_BY_KING = np.array([17, 38], dtype=np.int32)

THREAT_HANGING = np.array([13, 21], dtype=np.int32)

THREAT_RESTRICTED_PIECE = np.array([2, 0], dtype=np.int32)

THREAT_PAWN_PUSH = np.array([11, 10], dtype=np.int32)

SPACE_THRESHOLD = 4701

SPACE_BONUS_DIVISOR = 15

SPACE_SCALE_DIVISOR = 6

TEMPO_BONUS = 19

INITIATIVE_PASSED_WEIGHT_MG = 7

INITIATIVE_PAWN_WEIGHT_MG = 10

INITIATIVE_OUTFLANKING_WEIGHT_MG = 7

INITIATIVE_INFILTRATION_WEIGHT_MG = 9

INITIATIVE_BOTH_FLANKS_WEIGHT_MG = 15

INITIATIVE_PAWN_ENDGAME_WEIGHT_MG = 41

INITIATIVE_ALMOST_UNWIN_WEIGHT_MG = 33

INITIATIVE_OFFSET_MG = -78

INITIATIVE_MG_OFFSET = 39

INITIATIVE_PASSED_WEIGHT_EG = 5

INITIATIVE_PAWN_WEIGHT_EG = 5

INITIATIVE_OUTFLANKING_WEIGHT_EG = 3

INITIATIVE_INFILTRATION_WEIGHT_EG = 7

INITIATIVE_BOTH_FLANKS_WEIGHT_EG = 15

INITIATIVE_PAWN_ENDGAME_WEIGHT_EG = 28

INITIATIVE_ALMOST_UNWIN_WEIGHT_EG = 24

INITIATIVE_OFFSET_EG = -53

IMBALANCE_QUADRATIC_OURS = np.array([
    [1435, 0, 0, 0, 0, 0],
    [33, 23, 0, 0, 0, 0],
    [32, 249, -62, 0, 0, 0],
    [0, 95, 4, 0, 0, 0],
    [-23, -3, 44, 110, -207, 0],
    [-186, 19, 118, 137, -136, -6],
], dtype=np.int32)

IMBALANCE_QUADRATIC_THEIRS = np.array([
    [0, 0, 0, 0, 0, 0],
    [35, 0, 0, 0, 0, 0],
    [10, 69, 0, 0, 0, 0],
    [58, 71, 49, 0, 0, 0],
    [50, 45, 27, -23, 0, 0],
    [98, 104, -39, 138, 272, 0],
], dtype=np.int32)

IMBALANCE_DIVISOR = 20

IMBALANCE_SCALE_MG = 61

IMBALANCE_SCALE_EG = 51

KING_PROXIMITY_MAX_DIST = 6

KING_PROX_ENEMY_MULT = 7

KING_PROX_ENEMY_DIV = 4

KING_PROX_FRIENDLY_MULT = 1

KING_PROX_MIN_BONUS = -74

KING_PROX_MAX_BONUS = 79

UNSTOPPABLE_PAWN_BONUS = 800

KING_PAWN_PROXIMITY_FACTOR = 5
