# Updated constants generated by tuner.py
# Apply into chess_engine/classical/constants.py after review.
import numpy as np

MG_MATERIAL_VALUES = np.array([100, 347, 364, 572, 1170, 0], dtype=np.int32)

EG_MATERIAL_VALUES = np.array([117, 422, 437, 690, 1284, 0], dtype=np.int32)

PST_MG = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, -10, -10, -8, -5, -6, -9, 10, 4, -15, -23, -19, -11, -11, -5, -12, -7, -7, -16, -4, 6, 9, 0, 12, -10, 8, -1, -10, 15, 19, 9, 1, 12, 9, 11, 17, 27, 32, 16, 9, 16, 51, 50, 51, 49, 53, 45, 51, 49, 0, 0, 0, 0, 0, 0, 0, 0],
    [-45, -33, -34, -31, -24, -31, -40, -47, -42, -22, -7, -9, -6, 2, -19, -34, -27, -5, -4, 6, 12, 5, 8, -26, -11, 5, 13, 13, 12, 18, -4, -24, -27, 5, 13, 19, 11, 18, 10, -26, -25, 4, 11, 20, 13, 5, -1, -18, -48, -25, -3, 0, -2, -3, -20, -43, -38, -44, -40, -25, -32, -29, -46, -48],
    [-12, 6, -14, -10, -8, -18, -8, -19, -6, -10, 8, -14, -1, 3, 5, -12, -2, 14, -5, 8, 4, -3, 11, -3, -8, -3, 5, 11, 11, 7, -3, -5, -11, 3, 0, 9, 10, 8, 2, -6, -6, 10, 8, 13, 9, 1, -3, -5, -4, 2, 4, -3, 2, -1, -5, -7, -25, -8, -12, -6, -14, 0, -7, -20],
    [-11, -1, -1, 6, 4, -8, -3, 7, -6, 1, -4, 0, 2, 0, -1, -9, -7, -2, 0, -1, 4, -2, -1, -9, -6, 0, 5, 0, -1, 6, -4, -13, -8, 7, 2, 5, 1, 2, 2, -12, -3, 6, 0, -5, 5, -3, 2, -5, 8, 13, 10, 13, 17, 8, 12, 12, 5, -2, 1, 0, -2, -4, 3, -1],
    [-13, -8, -5, -10, -8, -13, -8, -22, -8, 0, 1, -2, -1, 5, 1, -6, -8, 3, 1, -6, -1, 12, 12, -1, 8, 0, 4, -5, 0, 7, 11, -4, -3, 2, 9, -4, 4, 2, 2, 5, -7, -2, 7, 5, 7, 5, -4, -6, -6, -3, 6, 2, -3, 4, 3, -9, -17, -10, -6, -7, -4, -15, -11, -19],
    [18, 34, 20, 2, 20, 8, 26, 17, 20, 24, -2, 1, -12, -7, 22, 17, -5, -16, -23, -21, -16, -24, -21, -10, -16, -30, -29, -44, -42, -36, -22, -17, -27, -41, -42, -51, -51, -38, -36, -32, -24, -34, -41, -54, -48, -38, -43, -28, -31, -37, -40, -50, -51, -40, -41, -24, -25, -45, -39, -52, -49, -37, -36, -31],
], dtype=np.int32)

PST_EG = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 12, 14, 15, 12, 26, 20, 10, -1, 9, 9, 10, 15, 11, 13, 6, 0, 10, 10, 5, 3, 4, 2, 4, 4, 26, 17, 14, 16, 8, 12, 17, 14, 49, 42, 43, 54, 49, 39, 43, 45, 74, 74, 85, 75, 79, 87, 74, 73, 0, 0, 0, 0, 0, 0, 0, 0],
    [-49, -35, -33, -27, -27, -33, -35, -50, -38, -21, -11, -4, -2, 2, -21, -37, -30, -7, 1, 11, 13, -5, -3, -28, -16, -2, 16, 15, 17, 16, 7, -21, -26, -2, 15, 20, 24, 17, 4, -22, -29, 1, 9, 13, 13, 8, 5, -39, -37, -17, -7, 14, 6, -6, -22, -38, -50, -43, -33, -31, -27, -27, -37, -56],
    [-35, -29, -22, -15, -17, -16, -35, -26, -20, -24, -9, -7, -4, -6, -22, -21, -17, 2, 0, 2, 2, -4, -2, -19, -16, -1, 3, 9, 9, 3, 1, -17, -18, 2, 12, 14, 6, 18, -3, -9, -18, 0, 3, 3, 3, 3, -7, 0, -29, -8, -17, 7, 4, -7, -16, -31, -44, -20, -31, -11, -12, -27, -25, -42],
    [-11, -17, -13, -13, -16, -9, -17, -20, -15, -11, -4, -5, -4, -3, -10, -15, 2, 0, -1, 1, -2, -6, 5, 4, -2, 5, 15, 2, 0, 8, 1, -5, 0, 7, 3, 10, 8, -1, 0, -4, 12, -1, 6, 12, 11, 0, -9, 9, 3, 3, 16, 2, 1, 20, 6, 6, 10, 6, 19, 16, 10, 19, 5, 18],
    [-65, -55, -47, -32, -34, -45, -54, -71, -56, -34, -22, -12, -13, -29, -31, -61, -41, -17, -13, -7, -4, -12, -21, -41, -32, -6, -2, 12, 17, 4, -6, -25, -27, 2, 13, 24, 24, 15, -2, -20, -43, -15, -8, 0, 4, -7, -20, -37, -50, -31, -19, -6, -1, -19, -25, -54, -74, -54, -44, -35, -38, -42, -44, -77],
    [-50, -25, -22, -28, -29, -27, -29, -52, -30, -24, -9, -8, -11, -12, -17, -31, -33, -12, 12, 9, 6, -1, -4, -28, -26, -7, 25, 29, 21, 16, -3, -25, -26, -6, 33, 38, 40, 33, -3, -25, -25, -7, 22, 33, 28, 20, -8, -24, -28, -9, -3, -2, -4, -6, -14, -30, -55, -38, -30, -21, -16, -27, -35, -49],
], dtype=np.int32)

KNIGHT_MOBILITY_BONUS = np.array([
    [-17, -26],
    [-16, -20],
    [0, -4],
    [2, 11],
    [3, 12],
    [6, 12],
    [10, 13],
    [11, 13],
    [13, 13],
], dtype=np.int32)

BISHOP_MOBILITY_BONUS = np.array([
    [-10, -18],
    [3, -11],
    [20, 3],
    [24, 10],
    [27, 23],
    [29, 29],
    [32, 32],
    [34, 37],
    [34, 37],
    [34, 37],
    [46, 37],
    [49, 38],
    [52, 41],
    [61, 42],
], dtype=np.int32)

ROOK_MOBILITY_BONUS = np.array([
    [-27, -32],
    [-4, -1],
    [9, 22],
    [13, 32],
    [13, 38],
    [15, 45],
    [16, 53],
    [18, 55],
    [24, 59],
    [25, 62],
    [26, 66],
    [27, 68],
    [28, 69],
    [28, 71],
    [33, 72],
], dtype=np.int32)

QUEEN_MOBILITY_BONUS = np.array([
    [-26, -10],
    [-14, -3],
    [5, 6],
    [12, 7],
    [20, 17],
    [25, 23],
    [25, 33],
    [29, 35],
    [32, 37],
    [34, 44],
    [37, 44],
    [37, 45],
    [41, 51],
    [41, 51],
    [41, 54],
    [42, 58],
    [43, 63],
    [44, 66],
    [45, 68],
    [55, 68],
    [57, 69],
    [58, 69],
    [61, 73],
    [63, 74],
    [65, 75],
    [66, 87],
    [74, 89],
    [75, 95],
], dtype=np.int32)

BISHOP_PAIR_BONUS = np.array([9, 15], dtype=np.int32)

BISHOP_PAIR_PAWN_SCALE = np.array([19, 33], dtype=np.int32)

ROOK_ON_SEMI_OPEN_FILE_BONUS = np.array([20, 3], dtype=np.int32)

ROOK_ON_OPEN_FILE_BONUS = np.array([24, 12], dtype=np.int32)

PASSED_PAWN_BONUS = np.array([
    [0, 0],
    [0, 3],
    [0, 0],
    [4, 23],
    [27, 42],
    [75, 76],
    [131, 108],
    [0, 0],
], dtype=np.int32)

PASSED_FILE_BONUS = np.array([15, 3], dtype=np.int32)

PASSED_CONNECTED_BONUS = np.array([0, 2, 3, 7, 17, 23, 57, 0], dtype=np.int32)

PASSED_PHALANX_BONUS = np.array([0, 1, 2, 13, 26, 42, 75, 0], dtype=np.int32)

CANDIDATE_PASSER_DIVISOR = 2

PASSED_PATH_SAFE_NONE_ATTACK = 11

PASSED_PATH_SAFE_EDGE_ATTACK = 7

PASSED_PATH_SAFE_BLOCK_ONLY = 3

PASSED_PATH_SUPPORT_BONUS = 4

PASSED_DYNAMICS_MULT = 4

PASSED_DYNAMICS_OFFSET = -11

ISOLATED_PAWN_PENALTY = np.array([-1, -7], dtype=np.int32)

DOUBLED_PAWN_PENALTY = np.array([-19, -37], dtype=np.int32)

BACKWARD_PAWN_PENALTY = np.array([0, -4], dtype=np.int32)

WEAK_LEVER_PENALTY = np.array([-5, -27], dtype=np.int32)

WEAK_UNOPPOSED_PENALTY = np.array([-14, -8], dtype=np.int32)

CONNECTED_BONUS = np.array([0, 1, 4, 4, 9, 37, 69, 0], dtype=np.int32)

CONNECTED_BONUS_EG = np.array([0, 2, 4, 11, 14, 23, 37, 0], dtype=np.int32)

CONNECTED_SUPPORT_WEIGHT = 11

CONNECTED_SUPPORT_WEIGHT_EG = 8

OUTPOST_BONUS_KNIGHT = np.array([
    [0, 0],
    [0, 0],
    [16, 4],
    [28, 16],
    [40, 24],
    [35, 24],
    [24, 5],
    [0, 0],
], dtype=np.int32)

OUTPOST_BONUS_BISHOP = np.array([
    [0, 0],
    [0, 0],
    [0, 3],
    [18, 13],
    [24, 17],
    [26, 20],
    [9, 4],
    [0, 0],
], dtype=np.int32)

REACHABLE_OUTPOST_BONUS = np.array([16, 14], dtype=np.int32)

MINOR_BEHIND_PAWN = np.array([11, 3], dtype=np.int32)

BISHOP_PAWNS_PENALTY = np.array([1, 2], dtype=np.int32)

BISHOP_PAWNS_CENTER_BLOCKED_FACTOR = 1

LONG_DIAGONAL_BISHOP = np.array([18, 6], dtype=np.int32)

TRAPPED_ROOK = np.array([11, 2], dtype=np.int32)

ROOK_ON_QUEEN_FILE = np.array([0, 2], dtype=np.int32)

WEAK_QUEEN = np.array([28, 1], dtype=np.int32)

KING_PROTECTOR = np.array([0, 0], dtype=np.int32)

KING_ATTACK_WEIGHTS = np.array([0, 0, 44, 12, 14, 1], dtype=np.int32)

SAFE_CHECK_QUEEN = 565

SAFE_CHECK_ROOK = 824

SAFE_CHECK_BISHOP = 477

SAFE_CHECK_KNIGHT = 609

KING_DANGER_WEAK_SQ = 111

KING_DANGER_UNSAFE_CHECK = 99

KING_DANGER_BLOCKERS = 70

KING_DANGER_ATTACK_ON_KING_SQ = 16

KING_DANGER_NO_QUEEN = 560

KING_DANGER_NO_QUEEN_ROOKLESS = 810

KING_DANGER_KNIGHT_DEF = 98

KING_DANGER_OFFSET = 0

KING_DANGER_THRESHOLD = 69

SHELTER_STRENGTH = np.array([
    [11, 49, 56, 51, 32, 21, 23, 0],
    [-35, 23, 22, -30, -25, -3, -48, 0],
    [3, 62, 24, 9, 25, -5, -39, 0],
    [-20, -4, -8, -17, -30, -51, -130, 0],
], dtype=np.int32)

UNBLOCKED_STORM = np.array([
    [-67, 219, 129, -70, -40, -36, -37, 0],
    [-28, 16, -91, -34, -28, -8, -18, 0],
    [14, -35, -129, -20, 1, 16, 27, 0],
    [6, 7, -78, -2, 4, 21, 15, 0],
], dtype=np.int32)

BLOCKED_STORM = -61

BLOCKED_STORM_EG = -41

SHELTER_BASE_MG = 20

SHELTER_BASE_EG = 5

KING_PAWN_DIST_PENALTY_EG = -6

PAWNLESS_FLANK = np.array([-13, -55], dtype=np.int32)

FLANK_ATTACKS = np.array([-1, 0], dtype=np.int32)

THREAT_SAFE_PAWN = np.array([69, 41], dtype=np.int32)

THREAT_KNIGHT_ON_QUEEN = np.array([9, 0], dtype=np.int32)

THREAT_SLIDER_ON_QUEEN = np.array([19, 0], dtype=np.int32)

THREAT_BY_MINOR = np.array([
    [4, 16],
    [23, 23],
    [52, 28],
    [73, 56],
    [50, 81],
    [0, 0],
], dtype=np.int32)

THREAT_BY_ROOK = np.array([
    [3, 21],
    [20, 29],
    [27, 25],
    [0, 22],
    [40, 22],
    [0, 0],
], dtype=np.int32)

THREAT_BY_KING = np.array([18, 38], dtype=np.int32)

THREAT_HANGING = np.array([12, 21], dtype=np.int32)

THREAT_RESTRICTED_PIECE = np.array([2, 0], dtype=np.int32)

THREAT_PAWN_PUSH = np.array([11, 12], dtype=np.int32)

SPACE_THRESHOLD = 4701

SPACE_BONUS_DIVISOR = 15

SPACE_SCALE_DIVISOR = 6

TEMPO_BONUS = 19

INITIATIVE_PASSED_WEIGHT_MG = 7

INITIATIVE_PAWN_WEIGHT_MG = 10

INITIATIVE_OUTFLANKING_WEIGHT_MG = 7

INITIATIVE_INFILTRATION_WEIGHT_MG = 9

INITIATIVE_BOTH_FLANKS_WEIGHT_MG = 15

INITIATIVE_PAWN_ENDGAME_WEIGHT_MG = 41

INITIATIVE_ALMOST_UNWIN_WEIGHT_MG = 33

INITIATIVE_OFFSET_MG = -78

INITIATIVE_MG_OFFSET = 39

INITIATIVE_PASSED_WEIGHT_EG = 5

INITIATIVE_PAWN_WEIGHT_EG = 4

INITIATIVE_OUTFLANKING_WEIGHT_EG = 3

INITIATIVE_INFILTRATION_WEIGHT_EG = 7

INITIATIVE_BOTH_FLANKS_WEIGHT_EG = 15

INITIATIVE_PAWN_ENDGAME_WEIGHT_EG = 28

INITIATIVE_ALMOST_UNWIN_WEIGHT_EG = 24

INITIATIVE_OFFSET_EG = -53

IMBALANCE_QUADRATIC_OURS = np.array([
    [1435, 0, 0, 0, 0, 0],
    [32, 21, 0, 0, 0, 0],
    [32, 249, -62, 0, 0, 0],
    [0, 95, 4, 0, 0, 0],
    [-23, -3, 44, 110, -207, 0],
    [-186, 19, 118, 137, -136, -6],
], dtype=np.int32)

IMBALANCE_QUADRATIC_THEIRS = np.array([
    [0, 0, 0, 0, 0, 0],
    [35, 0, 0, 0, 0, 0],
    [10, 69, 0, 0, 0, 0],
    [58, 72, 49, 0, 0, 0],
    [50, 45, 27, -23, 0, 0],
    [98, 105, -39, 138, 272, 0],
], dtype=np.int32)

IMBALANCE_DIVISOR = 21

IMBALANCE_SCALE_MG = 59

IMBALANCE_SCALE_EG = 52

KING_PROXIMITY_MAX_DIST = 6

KING_PROX_ENEMY_MULT = 7

KING_PROX_ENEMY_DIV = 4

KING_PROX_FRIENDLY_MULT = 1

KING_PROX_MIN_BONUS = -74

KING_PROX_MAX_BONUS = 79

UNSTOPPABLE_PAWN_BONUS = 800

KING_PAWN_PROXIMITY_FACTOR = 5
